import {
    Home,
    ClipboardList,
    MessageCircle,
    User,
    Bell,
    BellOff,
    Settings,
    ChevronRight,
    Plus,
    Search,
    MoreHorizontal,
    MoreVertical,
    ChevronDown,
    MapPin,
    LogOut,
    Clock,
    X,
    ArrowLeft,
    Check,
    Phone,
    Star,
    Dumbbell,
    Activity as ActivityIcon,
    Heart,
    Zap,
    Move,
    Target,
    Disc,
    PlusCircle,
    ChevronLeft,
    Briefcase,
    MessageSquare,
    Calendar,
    Download,
    Funnel
} from 'lucide-react';

export const ICONS = {
    home: Home,
    activity: ClipboardList,
    chat: MessageCircle,
    message: MessageSquare,
    profile: User,
    notification: Bell,
    bellOff: BellOff,
    settings: Settings,
    chevronRight: ChevronRight,
    chevronLeft: ChevronLeft,
    chevronDown: ChevronDown,
    briefcase: Briefcase,
    plus: Plus,
    search: Search,
    more: MoreHorizontal,
    moreVertical: MoreVertical,
    location: MapPin,
    logout: LogOut,
    clock: Clock,
    close: X,
    back: ArrowLeft,
    check: Check,
    phone: Phone,
    star: Star,
    dumbbell: Dumbbell,
    activityIcon: ActivityIcon,
    heart: Heart,
    zap: Zap,
    move: Move,
    target: Target,
    disc: Disc,
    plusCircle: PlusCircle,
    studio: Briefcase,
    calendar: Calendar,
    download: Download,
    filter: Funnel
};

export const ICON_CONFIG = {
    size: {
        nav: 22,
        header: 20,
        base: 18,
        small: 16
    },
    strokeWidth: 2,
    color: {
        active: '#5b5ff5',
        inactive: '#9CA3AF'
    }
};
